password: data?.employeePassword,
employee: {
  employeeId: data.employeeId,
  employeeEmail: data.employeeEmail,
  branchId: branchId,
  employeeName: data.name,
  joiningDate: data.joiningDate,
  employeeType: data.employeeType,
  phoneNo: data.phoneNo,
  employeeNid: data.employeeNid,
  address: data.presentAddress,
  fatherName: data.fatherName,
  motherName: data.motherName,
  bloodGroup: data.bloodGroup,
  degree: data.degree,
  basicSalary: Number(data.basicSalary),
  mobileBill: Number(data.mobileBill),
  conveyanceAllowance: Number(data.conveyanceAllowance),
  medicalAllowance: Number(data.medicalAllowance),
  houseRent: Number(data.houseRent),
  incentiveBonus: Number(data.incentiveBonus),
  others: Number(data.other),
  professionalTax: Number(data.professionalTax),
  incomeTax: Number(data.incomeTax),
  providentFund: Number(data.providentFund),
  totalSalary: Number(data.totalSalary),
  profileImage: uploadedImageUrl,
},


"password": "123456",
    "employee": {
        "employeeId": "EMP1234568",
        "employeeEmail": "employee5@gmail.com",
        "branchId": "652f9e812d5d4f089ae5d439",
        "employeeName": "John Doe",
        "joinigngDate": "2023-01-15",
        "employeeType": "Full-time",
        "phoneNo": "123-456-7890",
        "employeeNid": "9876543210",
        "presentAddress": "123 Main St, Cityville",
        "fatherName": "Michael Doe",
        "motherName": "Jane Doe",
        "bloodGroup": "O+",
        "degree": "Bachelor's in Computer Science",
        "basicSalary": 50000,
        "mobileBill": 2000,
        "conveyanceAllowance": 3000,
        "medicalAllowance": 1500,
        "houseRent": 8000,
        "incentiveBonus": 10000,
        "Others": 500,
        "prefessionalTax": 2500,
        "providentFund": 5000,
        "totalSalary": 70000,
        "profileImage": "https://example.com/profiles/john_doe.png"
    }